name: bulwark
services:
  solr:
    type: solr:5
    portforward: true
    run:
      - mkdir -p /opt/solr/server/solr/lib/contrib/
      - cp -r /opt/solr/contrib/analysis-extras/ /opt/solr/server/solr/lib/contrib/
      - solr delete -c lando # Deleting lando created core because it raises errors.
      - mkdir /opt/solr/bulwark-config # Copying solr config from docker container
      - curl -o /opt/solr/bulwark-config/schema.xml https://gitlab.library.upenn.edu/digital-repository/solr5_dev/-/raw/master/schema.xml
      - curl -o /opt/solr/bulwark-config/solrconfig.xml https://gitlab.library.upenn.edu/digital-repository/solr5_dev/-/raw/master/solrconfig.xml
      - solr create_core -c bulwark-development -d /opt/solr/bulwark-config
      - solr create_core -c bulwark-test -d /opt/solr/bulwark-config
  mysql:
    type: mysql:5.7.31
    portforward: 3307
  fcrepo:
    type: compose
    app_mount: false
    services:
      image: quay.io/upennlibraries/fcrepo_dev:latest
      command:
        - catalina.sh
        - run
      ports:
        - '8080:8080'
proxy:
  solr:
    - bulwark.solr.lndo.site:8983
  fcrepo:
    - bulwark.fcrepo.lndo.site:8080
