asset_extensions: &valid_asset_extensions
  - 'tif'
  - 'TIF'
  - 'tiff'
  - 'jpeg'
  - 'jpg'
  - 'pdf'
  - 'gz'
  - 'wav'

development:
  mounted_drives:
    test: <%= Rails.root.join('spec', 'fixtures', 'example_bulk_imports') %>
  marmite:
    url: http://marmite.library.upenn.edu:9292
  bulk_import:
    create_iiif_manifest: false
  digital_object:
    file_extensions: *valid_asset_extensions

test:
  mounted_drives:
    test: <%= Rails.root.join('spec', 'fixtures', 'example_bulk_imports') %>
  marmite:
    url: https://marmite.library.upenn.edu:9292
  bulk_import:
    create_iiif_manifest: false
  digital_object:
    file_extensions: *valid_asset_extensions

production:
  mounted_drives:
    kaplan-rescue: <%= ENV['KAPLAN_RESCUE_HARVESTING_ENDPOINT_REMOTE'] %>
    scanstore-rescue: <%= ENV['SCANSTORE_RESCUE_HARVESTING_ENDPOINT_REMOTE'] %>
    sceti-completed: <%= ENV['SCETI_COMPLETED_HARVESTING_ENDPOINT_REMOTE'] %>
    sceti-completed-2: <%= ENV['SCETI_COMPLETED_2_HARVESTING_ENDPOINT_REMOTE'] %>
    sceti-completed-3: <%= ENV['SCETI_COMPLETED_3_HARVESTING_ENDPOINT_REMOTE'] %>
    sceti-completed-4: <%= ENV['SCETI_COMPLETED_4_HARVESTING_ENDPOINT_REMOTE'] %>
    sceti: <%= ENV['SCETI_HARVESTING_ENDPOINT_REMOTE'] %>
    keffer: <%= ENV['KEFFER_HARVESTING_ENDPOINT_REMOTE'] %>
    fairmanrogers: <%= ENV['FAIRMANROGERS_HARVESTING_ENDPOINT_REMOTE'] %>
    mastersrbm:  <%= ENV['MASTERSRBM_HARVESTING_ENDPOINT_REMOTE'] %>
    managedmasters: <%= ENV['MANAGEDMASTERS_HARVESTING_ENDPOINT_REMOTE'] %>
  marmite:
    url: <%= ENV['MARMITE_URL'] %>
  bulk_import:
    create_iiif_manifest: true
  digital_object:
    file_extensions: *valid_asset_extensions
  phalt:
    url: <%= ENV['PHALT_ENDPOINT'] %>
  iiif:
    image_server: <%= ENV['IIIF_IMAGE_SERVER'] %>

