# Config file for working with the filesystem

defaults: &defaults
  object_derivatives_path: .derivs
  object_admin_path: .repoadmin
  object_data_path: data
  object_semantics_location: fs_semantics
  metadata_path_label: METADATA_PATH
  file_path_label: ASSETS_PATH
  init_script_permissions: a+x
  supported_vca_version: 6
  init_script_path: <%= Rails.root.join('docker', 'init.sh') %>
  mets_xml_derivative: mets.xml

development:
  <<: *defaults
  special_remote:
    type: directory
    name: local
    directory: <%= Rails.root.join('tmp', 'development_storage', 'special_remote') %>
  manifest_location: /Users/cgalarza/colenda_storage/manifest.txt
  remote_repo_permissions: =rx,ug+rwx
  workspace: <%= Rails.root.join('tmp', 'development_storage', 'scratch') %>
  assets_path: <%= Rails.root.join('tmp', 'development_storage', 'data') %>
  assets_display_path: <% Rails.root.join('tmp', 'development_storage', 'display') %>
  repository_prefix: DEV
  input_source_prefix: input_source
  problem_log: problems_log

test:
  <<: *defaults
  special_remote:
    type: directory
    name: local
    directory: <%= Rails.root.join('tmp', 'test_storage', 'special_remote') %>
  manifest_location: /path/to/manifest.txt
  remote_repo_permissions: =rx,ug+rwx
  metadata_path_label: metadata_label_in_manifest
  file_path_label: file_path_label_in_manifest
  workspace: <%= Rails.root.join('tmp', 'test_storage', 'scratch') %>
  assets_path: <%= Rails.root.join('tmp', 'test_storage', 'data') %>
  assets_display_path: <% Rails.root.join('tmp', 'test_storage', 'display') %>
  repository_prefix: TEST

production:
  special_remote:
    type: <%= ENV['STORAGE_TYPE'] %>
    name: <%= ENV['SPECIAL_REMOTE_NAME'] %>
  manifest_location: /home/app/webapp/docker/manifest.txt
  mets_xml_derivative: mets.xml
  object_admin_path: .repoadmin
  object_derivatives_path: .derivs
  object_semantics_location: fs_semantics
  remote_repo_permissions: =rx,ug+rwx
  init_script_path: /home/app/webapp/docker/init.sh
  init_script_permissions: a+x
  object_data_path: data
  workspace: /fs/priv/workspace
  assets_path: /fs/pub/data
  assets_display_path: /fs/pub/display
  metadata_path_label: METADATA_PATH
  file_path_label: ASSETS_PATH
  repository_prefix: UPENNLIB
  supported_vca_version: 6
  input_source_prefix: input_source
  problem_log: problems_log
