# Settings for development environment.

mounted_drives:
  test: <%= Rails.root.join('spec', 'fixtures', 'example_bulk_imports') %>
marmite:
  url: http://marmite.library.upenn.edu:9292
bulk_import:
  create_iiif_manifest: false
digital_object:
  git_annex_version: 6
  repository_prefix: DEV
  special_remote:
    type: directory
    name: local
    directory: <%= Rails.root.join('tmp', 'development_storage', 'special_remote') %>
  workspace_path: <%= Rails.root.join('tmp', 'development_storage', 'scratch') %>
  remotes_path: <%= Rails.root.join('tmp', 'development_storage', 'data') %>
  default_paths:
    admin_directory: .repoadmin
    derivatives_directory: .derivs
    data_directory: data
    semantics_filename: fs_semantics
phalt:
iiif:

# Apotheca File Storage
aws: &aws
  access_key_id: minioadmin
  secret_access_key: minioadmin
  endpoint: http://minio-dev.library.upenn.edu
  region: us-east-1
  force_path_style: true
preservation_storage:
  <<: *aws
  bucket: preservation-dev
derivative_storage:
  <<: *aws
  bucket: derivatives-dev
iiif_manifest_storage:
  <<: *aws
  bucket: iiif-manifests-dev

# Publishing Endpoint
publishing_endpoint:
  token: sample_token