# Settings for development environment.

mounted_drives:
  test: <%= Rails.root.join('spec', 'fixtures', 'example_bulk_imports') %>
marmite:
  url: http://marmite.library.upenn.edu:9292
bulk_import:
  create_iiif_manifest: false
digital_object:
  git_annex_version: 6
  repository_prefix: DEV
  special_remote:
    type: directory
    name: local
    directory: <%= Rails.root.join('tmp', 'development_storage', 'special_remote') %>
  workspace_path: <%= Rails.root.join('tmp', 'development_storage', 'scratch') %>
  remotes_path: <%= Rails.root.join('tmp', 'development_storage', 'data') %>
  default_paths:
    admin_directory: .repoadmin
    derivatives_directory: .derivs
    data_directory: data
    semantics_filename: fs_semantics
phalt:
iiif: