# Settings for all deployed environment.

mounted_drives:
  sceti-completed-4: <%= ENV['SCETI_COMPLETED_4_HARVESTING_ENDPOINT_REMOTE'] %>
  sceti-completed-5: <%= ENV['SCETI_COMPLETED_5_HARVESTING_ENDPOINT_REMOTE'] %>
marmite:
  url: <%= ENV['MARMITE_URL'] %>
bulk_import:
  create_iiif_manifest: true
digital_object:
  git_annex_version: 6
  repository_prefix: UPENNLIB
  special_remote:
    type: <%= ENV['STORAGE_TYPE'] %>
    name: <%= ENV['SPECIAL_REMOTE_NAME'] %>
    port: <%= ENV["STORAGE_PORT"] %>
    host: <%= ENV["STORAGE_HOST"] %>
    protocol: <%= ENV["STORAGE_PROTOCOL"] %>
    encryption: <%= ENV["STORAGE_ENCRYPTION"] %>
    request_style: <%= ENV["REQUEST_STYLE"] %>
    public: '<%= ENV["STORAGE_PUBLIC"] %>'
    aws_access_key_id: <%= File.exist?('/run/secrets/aws_access_key_id') ? File.read('/run/secrets/aws_access_key_id').strip : nil %>
    aws_secret_access_key: <%= File.exist?('/run/secrets/aws_secret_access_key') ? File.read('/run/secrets/aws_secret_access_key').strip : nil %>
  workspace_path: /fs/priv/workspace
  remotes_path: /fs/pub/data
  default_paths:
    admin_directory: .repoadmin
    derivatives_directory: .derivs
    data_directory: data
    semantics_filename: fs_semantics
phalt:
  url: <%= ENV['PHALT_ENDPOINT'] %>
iiif:
  image_server: <%= ENV['IIIF_IMAGE_SERVER'] %>

# Apotheca File Storage
aws: &aws
  access_key_id: <%= File.exist?('/run/secrets/s3_access_key_id') ? File.read('/run/secrets/s3_access_key_id').strip : nil %>
  secret_access_key: <%= File.exist?('/run/secrets/s3_secret_access_key') ? File.read('/run/secrets/s3_secret_access_key').strip : nil %>
  region: <%= File.exist?('/run/secrets/s3_region') ? File.read('/run/secrets/s3_region').strip : 'us-east-1' %>
preservation_storage:
  <<: *aws
  bucket: <%= ENV['S3_PRESERVATION_BUCKET'] %>
derivative_storage:
  <<: *aws
  bucket: <%= ENV['S3_DERIVATIVES_BUCKET'] %>
iiif_manifest_storage:
  <<: *aws
  bucket: <%= ENV['S3_IIIF_MANIFEST_BUCKET'] %>

# Publishing endpoint
publishing_endpoint:
  token:  <%= File.exist?('/run/secrets/publishing_token') ? File.read('/run/secrets/publishing_token').strip : nil %>